// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjlzrvqvmcknuxjkuiac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbHpydnF2bWNrbnV4amt1aWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Mjk4MDUsImV4cCI6MjA3MzUwNTgwNX0.xWCKrGF3hfedvJfUvEUYpd1u05P73GCBAPElxxR8-lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});